language: android

android:
  components:
  - tools
  - platform-tools
  - tools
  - extra
  - build-tools-25.0.1
  - android-26

jdk:
- oraclejdk8

before_install:
- nvm install 6

install:
- npm install -g cordova
- npm install

script:
- npm run build --prod
- cordova plugin add cordovarduino
- cordova platform add android
- cordova build android
