matrix:
  include:
  - language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - extra
      - build-tools-28.0.3
      - android-28
    env: TARGET_PLATFORM=android
  - language: objective-c
    osx_image: xcode9.4
    env: TARGET_PLATFORM=ios

before_install:
- nvm install 10

install:
- npm install -g cordova
- npm install

script:
- npm run build --prod
- cordova platform add "$TARGET_PLATFORM"
- cordova build "$TARGET_PLATFORM"
